export const SKILL_CATEGORIES = [
  "SOFTWARE_DEVELOPMENT",
  "DATA_SCIENCE",
  "MACHINE_LEARNING",
  "ARTIFICIAL_INTELLIGENCE",
  "DATABASES",
  "DEVOPS",
  "CLOUD",
  "VERSION_CONTROL",
  "TESTING",
  "UI_UX",
  "SOFT_SKILLS"
];