export const SKILL_CATEGORIES = [
  "SOFTWARE_DEVELOPMENT",
  "FRONTEND",
  "BACKEND",
  "DATABASES",
  "DEVOPS",
  "CLOUD",
  "DATA_ANALYTICS",
  "DATA_SCIENCE",
  "MACHINE_LEARNING",
  "ARTIFICIAL_INTELLIGENCE",
  "COMPUTER_VISION",
  "NLP_LLM",
  "MLOPS",
  "UI_UX",
  "TESTING",
  "VERSION_CONTROL",
  "SOFT_SKILLS"
];


