export const SKILL_CATEGORIES = [
  "LANGUAGE",
  "CS_FUNDAMENTALS",
  "FRONTEND",
  "BACKEND",
  "DATABASE",
  "FRAMEWORK",
  "ML_AI",
  "TOOLS",
  "CLOUD",
  "DATA_ANALYSIS",
  "DATA_VISUALIZATION",
];